apiVersion: install.verrazzano.io/v1alpha1
kind: Verrazzano
metadata:
  name: VZ_INSTALLATION_NAME
spec:
  profile: VZ_PROFILE
  components:
    ingress:
      type: NodePort
      nginxInstallArgs:
       - name: controller.service.externalIPs
         valueList:
          - 150.230.184.190
      ports:
       - name: custom-http-port
         nodePort: 30080
         port: 80
         protocol: TCP
         targetPort: 80
       - name: custom-https-port
         nodePort: 30443
         port: 443
         protocol: TCP
         targetPort: 443
