name: Setup Verrazzano on OKE multi cluster
on: [push]
jobs:
  create_oke_admin_cluster:
    uses: ta9846/git-actions-demo/.github/workflows/create_oke_cluster.yml@vz_oke_multi_cluster
    with: 
       username: ta9846
    secrets:
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      
  cleanup-oke_admin_cluster:
    uses: ta9846/git-actions-demo/.github/workflows/cleanup_oke_cluster.yml@vz_oke_multi_cluster
    needs: create_oke_admin_cluster
    if: always()
    secrets: 
       CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
