name: Deploy Verrazzano
on:
  workflow_call:
    inputs:
      vz_crd_filename:
        required: false
        type: string
      CUSTOM_CA_OPTION:
        required: false
        type: boolean
jobs:
  test_checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: List checked-out files
        if: ${{inputs.CUSTOM_CA_OPTION}}
        run: |
          echo "Custom CA option is true"
          echo $(pwd)
          cat ${{ inputs.vz_crd_filename }}
          echo ${{inputs.CUSTOM_CA_OPTION}}
      - name: Check boolean input
        if: ${{inputs.CUSTOM_CA_OPTION}} == false
        run: echo "Custom CA option is false"          
