name: Test checkout workflow
on: [push]
jobs:
  test_checkout:
    uses: ta9846/git-actions-demo/.github/workflows/test_checkout.yml@develop
    if: always()
    with:
      vz_crd_filename: vz_crd_default.yml
      CUSTOM_CA_OPTION: true
