name: Test checkout
on:
  workflow_call:
    inputs:
      vz_crd_filename:
        required: false
        type: string
      CUSTOM_CA_OPTION:
        required: false
        type: string
jobs:
  test_checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Export env
        env:
          ca_option: ${{inputs.CUSTOM_CA_OPTION}}
        run: |
          echo "env.ca_option: ${{env.ca_option}}"
          echo "input.ca_option: ${{inputs.CUSTOM_CA_OPTION}}"
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: List checked-out files
        if: contains(${{inputs.CUSTOM_CA_OPTION}}, 'true')
        run: |
          echo "Custom CA option is true"
          echo $(pwd)
          cat ${{ inputs.vz_crd_filename }}
          echo ${{inputs.CUSTOM_CA_OPTION}}
      - name: Run if CUSTOM_CA_OPTION is false
        if: contains(${{inputs.CUSTOM_CA_OPTION}}, 'false')
        run: echo "Custom CA option is false"          
